name: java
version: 4.22.0-beta
schema: 1
scm: github.com/pubnub/java
files:
  - build/libs/pubnub-gson-4.22.0-beta-all.jar
changelog:
  - version: v4.22.0-beta
    date: 2018-01-31
    changes:
      - type: feature
        text: Update 3rd party libraries
  - version: v4.21.0
    date: 2018-10-26
    changes:
      - type: feature
        text: Support optional query parameters for every request
      - type: feature
        text: Update documentation
  - version: v4.20.0
    date: 2018-08-07
    changes:
      - type: bug
        text: Fix an issue where the global-here-now response was interpreted incorrectly
  - version: v4.19.0
    date: 2018-03-29
    changes:
      - type: bug
        text: Fix an issue where end of channel history was interpreted as an error
  - version: v4.18.0
    date: 2018-01-11
    changes:
      - type: improvement
        text: lock down okHTTP version to support latest android version
  - version: v4.17.0
    date: 2017-12-19
    changes:
      - type: improvement
        text: allow SDK to only send heartbeats without subscribing to the data channel.
  - version: v4.16.0
    date: 2017-11-21
    changes:
      - type: improvement
        text: allow setting setMaximumConnections to open more connections to PubNub
  - version: v4.15.0
    date: 2017-11-17
    changes:
      - type: improvement
        text: update gson dependency
      - type: bug
        text: make listeners thread safe
      - type: bug
        text: close hanging threads on shutdown
  - version: v4.14.0
    date: 2017-10-25
    changes:
      - type: improvement
        text: add support to supress leave events
  - version: v4.13.0
    date: 2017-10-23
    changes:
      - type: improvement
        text: do not execute subscribe on empty string channel, channel groups
      - type: improvement
        text: stop heartbeat loop if an error shows up.
  - version: v4.12.0
    date: 2017-10-05
    changes:
      - type: bug
        text: fix worker thread unloading.
      - type: feature
        text: prevent concurrent modification of listeners.
  - version: v4.11.0
    date: 2017-10-05
    changes:
      - type: bug
        text: fix retrofit unloading.
  - version: v4.10.0
    date: 2017-09-17
    changes:
      - type: feature
        text: rework the loading of services to load the classes once.
  - version: v4.9.1
    date: 2017-08-14
    changes:
      - type: feature
        text: patch-up to the deduping algorithm
  - version: v4.9.0
    date: 2017-08-14
    changes:
      - type: feature
        text: Internal deduping mechanism when devices cross regions (dedupOnSubscribe).
  - version: v4.8.0
    date: 2017-08-08
    changes:
      - type: feature
        text: Allow certificate pinning via setCertificatePinner on PNConfiguration
      - type: feature
        text: Allow disabling of heartbeat by setting the interval to 0.
      - type: feature
        text: GAE fixes.
  - version: v4.7.0
    date: 2017-07-20
    changes:
      - type: feature
        text: Allow injection of httpLoggingInterceptor for extra logging monitoring..
  - version: v4.6.5
    date: 2017-06-28
    changes:
      - type: bug
        text: adjust queue exceeded notifications to be greater or equal of.
  - version: v4.6.4
    date: 2017-06-10
    changes:
      - type: bug
        text: gracefully handle disabled history
  - version: v4.6.3
    date: 2017-06-03
    changes:
      - type: feature
        text: on interval events, pass hereNowRefresh to indicate if a here_now fetch is needed.
  - version: v4.6.2
    date: 2017-04-13
    changes:
      - type: feature
        text: set a name for Subscription Manager Consumer Thead.
  - version: v4.6.1
    date: 2017-04-06
    changes:
      - type: bug
        text: SDK crash in Android with Airplane Mode
      - type: feature
        text: add deltas on interval action.
  - version: v4.6.0
    date: 2017-03-14
    changes:
      - type: feature
        text: To distinguish UUID's that were generated by our SDK, we appended `pn-` before the UUID to signal that it's a randomly generated UUID.
      - type: feature
        text: Allow the passing of okHttp connection spec via setConnectionSpec
      - type: improvement
        text: Bump retrofit to 2.2.0
  - version: v4.5.0
    date: 2017-02-15
    changes:
      - type: feature
        text: add .toString methods to all public facing models and POJOs
  - version: v4.4.4
    date: 2017-02-06
    changes:
      - type: feature
        text: Add support to configure host name verifier.
  - version: v4.4.3
    date: 2017-02-02
    changes:
      - type: feature
        text: Add support to configure custom certificate pinning via SSLSocketFactory and X509 configuration objects.
  - version: v4.4.2
    date: 2017-01-31
    changes:
      - type: bug
        text: SDK was not sending the user metadata on Message Callback
  - version: v4.4.1
    date: 2017-01-25
    changes:
      - type: bug
        text: SDK did not honor the exhaustion of reconnections, it will now disconnect once max retries happened
  - version: v4.4.0
    date: 2017-01-24
    changes:
      - type: improvement
        text: Support for maximum reconnection attempts
      - type: improvement
        text: Populate affectedChannel and affectedChannelGroups
      - type: improvement
        text: Support for GAE
      - type: improvement
        text: Emit pnconnected when adding / removing channels.
  - version: v4.3.1
    date: 2016-12-22
    changes:
      - type: improvement
        text: support for key-level grant.
  - version: v4.3.0
    date: 2016-12-14
    changes:
      - type: improvement
        text: JSON parser is switched to GSON, new artifact on nexus as pubnub-gson
      - type: improvement
        text: GetState, setState return a JsonElement instead of a plain object.
  - version: v4.2.3
    date:
    changes:
      - type: improvement
        text: Swapping out logger for slf4japi and removing final methods
  - version: v4.2.2
    date: 2016-12-09
    changes:
      - type: improvement
        text: remove final identifiers from the public facing API.
  - version: v4.2.1
    date: 2016-11-23
    changes:
      - type: improvement
        text: include publisher UUID on incoming message
      - type: improvement
        text: allow to set custom TTL on a publish
  - version: v4.2.0
    date: 2016-10-25
    changes:
      - type: improvement
        text: Signatures are generated for all requests with secret key to ensure secure transmission of data
      - type: improvement
        text: support for alerting of queue exceeded (PNRequestMessageCountExceededCategory)
      - type: improvement
        text: signaling to okhttp to stop the queues on termination.
  - version: v4.1.0
    date: 2016-10-12
    changes:
      - type: improvement
        text: destory now correctly forces the producer thread to shut down; stop is now deprecated for disconnect
      - type: improvement
        text: support for sending instance id for presence detection (disabled by default)
      - type: improvement
        text: support for sending request id to burst cache (enabled by default)
      - type: improvement
        text: proxy support via the native proxy configurator class.
  - version: v4.0.14
    date: 2016-09-20
    changes:
      - type: improvement
        text: on PAM error, populate the affectedChannel or affectedChannelGroup to signal which channels are failing
  - version: v4.0.13
    date: 2016-09-14
    changes:
      - type: improvement
        text: populate jso with the error.
  - version: v4.0.12
    date: 2016-09-13
    changes:
      - type: bug
        text: fixing parsing of origination payload within the psv2 enevelope
  - version: v4.0.11
    date: 2016-09-09
    changes:
      - type: improvement
        text: bumping build process for gradle 3 / merging documentation into the repo and test adjustments
  - version: v4.0.10
    date: 2016-09-07
    changes:
      - type: improvement
        text: adding channel / channelGroup fields when a message / presence event comes in.
  - version: v4.0.9
    date: 2016-08-24
    changes:
      - type: improvement
        text: adjustments for handling pn_other and decryption
      - type: improvement
        text: retrofit version bumps.
  - version: v4.0.8
    date: 2016-08-16
    changes:
      - type: feature
        text: added unsubscribeAll, getSubscribedChannels, getSubscribedChannelGroups
      - type: feature
        text: SDK will establish secure connections by default
      - type: feature
        text: added support for exponential backoff reconnection policies
  - version: v4.0.7
    date: 2016-08-11
    changes:
      - type: improvement
        text: reduce overlap on error handling when returning exceptions.
  - version: v4.0.6
    date: 2016-07-18
    changes:
      - type: improvement
        text: send heartbeat presence value when subscribing
  - version: v4.0.5
    date: 2016-07-07
    changes:
      - type: improvement
        text: unified retrofit handling to lower amount of instances and sync'd the state methods.
  - version: v4.0.4
    date: 2016-06-24
    changes:
      - type: bug
        text: setting State for other UUID's is now supported.
  - version: v4.0.3
    date: 2016-06-15
    changes:
      - type: feature
        text: fire() method and no-replicaton options.
  - version: v4.0.2
    date: 2016-06-15
    changes:
      - type: bug
        text: fix to the version fetching.
  - version: v4.0.1
    date: 2016-06-06
    changes:
      - type: bug
        text: adjustment of the subscribe loop to alleviate duplicate dispatches.
  - version: v4.0.0
    date: 2016-06-03
    changes:
      - type: bug
        text: first GA.
  - version: v4.0.0-beta4
    changes:
      - type: improvement
        text: reconnects and minor adjustments.
  - version: v4.0.0-beta3
    changes:
      - type: bug
        text: fixing state not coming on the subscriber callback.
      - type: bug
        text: adjustments to URL encoding on publish, subscribe, set-state operations to avoid double encoding with retrofit.
  - version: v4.0.0-beta2
    changes:
      - type: improvement
        text: reworking of message queue.
      - type: improvement
        text: checkstyle, findbugs.
      - type: improvement
        text: reworking error notifications.
  - version: v4.0.0-beta1
    changes:
      - type: improvement
        text: initial beta1.
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-FETCH-MESSAGES
    - STORAGE-DELETE-MESSAGES
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
supported-platforms:
  - version: PubNub Java SDK
    platforms:
      - Windows 10 (7u85 and above)
      - Windows 8.x (Desktop)
      - Windows 7 SP1
      - Windows Vista SP2
      - Windows Server 2008 SP2 and 2008 R2 SP1 (64-bit)
      - Windows Server 2012 (64-bit) and 2012 R2 (64-bit)
      - Intel-based Mac running Mac OS X 10.7.3 (Lion) or later.
      - Oracle Linux 5.5+
      - Oracle Linux 6.x (32-bit), 6.x (64-bit)3
      - Oracle Linux 7.x (64-bit)3 (7u67 and above)
      - Red Hat Enterprise Linux 5.5+, 6.x (32-bit), 6.x (64-bit)3
      - Red Hat Enterprise Linux 7.x (64-bit)3 (7u67 and above)
      - Suse Linux Enterprise Server 10 SP2, 11.x
      - Suse Linux Enterprise Server 12.x (7u75 and above)
      - Ubuntu Linux 10.04 and above
    editors:
      - Java7+
  - version: PubNub Android SDK
    platforms:
      - Android 4.0+
